# Especifica un dominio local (e.g., miapp.com) para que apunte a la IP de tu aplicación(ip anfitrion)
address=/miapp.com/192.168.1.64

# Opcional: Limita las interfaces si lo necesitas
interface=eth0

# Servidores DNS externos para hacer forward de solicitudes no locales (Google DNS)
server=8.8.8.8
server=8.8.4.4

# Evita usar resoluciones del sistema anfitrión
no-resolv
