server {
  listen 80;
  server_name miapp.com;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    # Si la ruta no es un archivo o directorio, redirige a index.html
    try_files $uri $uri/ /index.html;
  }
}